apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: spark-operator
  template:
    metadata:
      labels:
        name: spark-operator
    spec:
      serviceAccountName: spark-operator
      containers:
        - name: spark-operator
          # Replace this with the built image name
          image: yobitel/spark-operator:2.4.5
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "spark-operator"
